# Use Node.js LTS official image
FROM node:23-slim

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the app code
COPY . .

# Expose port
EXPOSE 5000

# Start app
CMD ["node", "app.js"]
